<<<<<<<<<<<<<<<<<<<PART 1 FINISHED>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<PART 2 FINISHED>>>>>>>>>>>>>>>>>>>>>>>>
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:67: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_literals / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:91: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_ternary / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:83: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_functions / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:67: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_literals / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:91: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_ternary / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:83: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_functions / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:67: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_literals / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:91: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_ternary / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:83: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_functions / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:91: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_ternary / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:67: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_literals / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/features/lexical.py:83: RuntimeWarning: divide by zero encountered in log
  value = np.log(num_functions / file_length)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "De-anonymizing_Programmers_via_Code_Stylometry.py", line 93, in <module>
    samplesdf = pd.DataFrame(samples) 
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/frame.py", line 450, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/internals/construction.py", line 467, in to_arrays
    data, columns, coerce_float=coerce_float, dtype=dtype
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/internals/construction.py", line 569, in _list_of_dict_to_arrays
    content = list(lib.dicts_to_array(data, list(columns)).T)
  File "pandas/_libs/lib.pyx", line 325, in pandas._libs.lib.dicts_to_array
MemoryError: Unable to allocate 144. GiB for an array with shape (65120, 297578) and data type object
